/**
 * Test fixtures — Noticias reales de Nicaragua Informate
 * =================================
 * Casos de prueba para Editor IA V4.
 * Cada fixture tiene: noticia input + categoría esperada + score mínimo esperado + veredicto esperado.
 */

import type { NoticiaInput } from '../../lib/analizador-noticias';

export interface TestFixture {
  nombre: string;
  noticia: NoticiaInput;
  categoriaEsperada: string;
  scoreMinimo: number;
  veredictoEsperado: string;
  descripcion: string;
}

// ───────────────────────────────────────────────
// SUCESOS — 20 casos
// ───────────────────────────────────────────────

export const sucesosFixtures: TestFixture[] = [
  {
    nombre: 'sucesos-01-incautacion-marihuana',
    noticia: {
      titulo: 'Incautan 293 libras de marihuana en El Guasaule, Chinandega',
      contenido: '<p>La Policía Nacional incautó 293 libras de marihuana ocultas en un compresor en El Guasaule, Chinandega. Un guatemalteco fue detenido cuando viajaba hacia Costa Rica.</p><p>Según el parte policial, el decomiso ocurrió en un punto de control en la carretera. El decomiso fue uno de los más grandes del año en la región.</p><p>Las autoridades indicaron que la sustancia iba camuflada dentro de un compresor de aire. El detenido será presentado ante las autoridades competentes.</p>',
      resumen: 'La Policía Nacional incautó 293 libras de marihuana ocultas en un compresor en El Guasaule. Un guatemalteco fue detenido cuando viajaba hacia Costa Rica.',
      categoria: 'Sucesos',
      autor: 'Keyling Elieth Rivera Muñoz',
      fecha: '2025-07-15',
      slug: 'incautan-293-libras-marihuana-guasaule-chinandega',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 60,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Nota de sucesos con fuente oficial, datos concretos y contexto',
  },
  {
    nombre: 'sucesos-02-accidente-transito',
    noticia: {
      titulo: 'Accidente en carretera Masaya deja 3 heridos',
      contenido: '<p>Tres personas resultaron heridas en un accidente de tránsito en la carretera Masaya, a la altura del km 12. Según testigos, una camioneta y un motociclista colisionaron.</p><p>Los heridos fueron trasladados al hospital Bertha Calderón. El motociclista presenta lesiones de consideración.</p><p>Bomberos arrived al lugar para auxiliar a los heridos. El tránsito fue desviado por una hora.</p>',
      resumen: 'Tres heridos en accidente en carretera Masaya km 12. Testigos reportan colisión entre camioneta y motociclista.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-14',
      slug: 'accidente-carretera-masaya-3-heridos',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Accidente con testigos, heridos, hospital y ubicación',
  },
  {
    nombre: 'sucesos-03-incendio-casa',
    noticia: {
      titulo: 'Incendio consume vivienda en barrio Luisa Valenzuela',
      contenido: '<p>Una vivienda fue consumida por el fuego en el barrio Luisa Valenzuela de Managua. Vecinos reportaron que el incendio inició a las 2:00 de la madrugada.</p><p>Bomberos del cuartel central acudieron al lugar y lograron controlar las llamas en 40 minutos. No se reportaron víctimas.</p><p>Según vecinos, el incendio pudo haberse originado por un cortocircuito. Las pérdidas se calculan en más de C$50,000.</p>',
      resumen: 'Vivienda destruida por incendio en barrio Luisa Valenzuela. Bomberos controló las llamas sin víctimas.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-13',
      slug: 'incendio-vivienda-barrio-luisa-valenzuela',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Incendio con ubicación, hora, fuente vecinal y datos',
  },
  {
    nombre: 'sucesos-04-robo-comercio',
    noticia: {
      titulo: 'Sujeto es detenido tras robar comercio en Granada',
      contenido: '<p>Un sujeto fue detenido tras robar un comercio en el centro de Granada. Según el comerciante, el individuo sustrajo C$15,000 en efectivo.</p><p>Testigos del lugar alertaron a la policía que llegó en minutos. El detenido fue identificado como residente de la zona.</p><p>El comerciante indicó que este es el tercer robo en el sector en lo que va del mes.</p>',
      resumen: 'Detenido tras robar C$15,000 de comercio en Granada. Testigos alertaron a la policía.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-12',
      slug: 'detenido-robo-comercio-granada',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Robo con testigos, monto y detención',
  },
  {
    nombre: 'sucesos-05-ahogado-playa',
    noticia: {
      titulo: 'Joven pierde la vida en playa de San Juan del Sur',
      contenido: '<p>Un joven de 22 años perdió la vida tras ahogarse en la playa de San Juan del Sur. Según familiares, el joven ingresó al mar en horas de la tarde.</p><p>Bomberos y rescatistas de la zona realizaron labores de búsqueda. El cuerpo fue encontrado dos horas después.</p><p>Esta es la segunda víctima por ahogamiento en las playas del Pacífico en la temporada.</p>',
      resumen: 'Joven de 22 años ahogado en playa de San Juan del Sur. Cuerpo encontrado dos horas después.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-11',
      slug: 'joven-ahogado-playa-san-juan-sur',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Ahogamiento con fuente familiar, ubicación y contexto',
  },
  {
    nombre: 'sucesos-06-detencion-pandilla',
    noticia: {
      titulo: 'Caen cuatro miembros de pandilla en Estelí',
      contenido: '<p>Cuatro miembros de una pandilla fueron detenidos en el barrio 15 de Septiembre de Estelí. Según la Policía, el grupo era señalado de múltiples delitos en el sector.</p><p>Los detenidos serán presentados ante la autoridad competente. Se les imputan cargos por roo, lesiones y tenencia ilegal de armas.</p><p>Vecinos del sector indicaron que la zona había mejorado en seguridad en los últimos meses.</p>',
      resumen: 'Cuatro pandilleros detenidos en barrio 15 de Septiembre de Estelí. Señalados de robo y lesiones.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-10',
      slug: 'detencion-pandilla-esteli',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Detención con fuente policial y contexto vecinal',
  },
  {
    nombre: 'sucesos-07-fuga-gas',
    noticia: {
      titulo: 'Fuga de gas obliga evacuación en León',
      contenido: '<p>Una fuga de gas obligó la evacuación de cinco viviendas en el barrio Suburbio de León. Bomberos acudieron al lugar y lograron controlar la fuga.</p><p>Según el cuerpo de Bomberos, la fuga se originó por una válvula defectuosa en un cilindro. No se reportaron heridos.</p><p>Los vecinos fueron autorizados a regresar a sus viviendas una hora después.</p>',
      resumen: 'Fuga de gas evacúa cinco viviendas en barrio Suburbio de León. Bomberos controló sin heridos.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-09',
      slug: 'fuga-gas-evacuacion-leon',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Fuga de gas con fuente de Bomberos y ubicación',
  },
  {
    nombre: 'sucesos-08-caida-arbol',
    noticia: {
      titulo: 'Árbol cae sobre vehículo en Carretera Sur',
      contenido: '<p>Un árbol cayó sobre un vehículo estacionado en la Carretera Sur a la altura del km 8. Según el conductor, el árbol cayó de manera repentina.</p><p>Bomberos retiraron el árbol y se reportaron daños materiales. No hubo heridos.</p><p>Vecinos indicaron que el árbol presentaba señales de deterioro desde hace meses.</p>',
      resumen: 'Árbol cae sobre vehículo en Carretera Sur km 8. Daños materiales sin heridos.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-08',
      slug: 'arbol-cae-vehiculo-carretera-sur',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 45,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Caida de árbol con testigo y ubicación',
  },
  {
    nombre: 'sucesos-09-descomposición-alimentos',
    noticia: {
      titulo: 'Decomisan 200 libras de carne en mal estado en mercado',
      contenido: '<p>Autoridades sanitarias decomisaron 200 libras de carne en mal estado en el Mercado Oriental de Managua. El decomiso se realizó tras una inspección de rutina.</p><p>Según los inspectores, la carne no contaba con los sellos sanitarios correspondientes. El producto fue destruido.</p><p>El comerciante fue multado y se inició un proceso administrativo.</p>',
      resumen: 'Decomisan 200 libras de carne en mal estado en Mercado Oriental. Sin sellos sanitarios.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-07',
      slug: 'decomisan-carne-mal-estado-mercado-oriental',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Decomiso con inspectores, cantidad y ubicación',
  },
  {
    nombre: 'sucesos-10-rescate-migrantes',
    noticia: {
      titulo: 'Rescatan a 15 migrantes en ruta hacia Costa Rica',
      contenido: '<p>Quince migrantes fueron rescatados en una operación en la frontera sur de Nicaragua. Según autoridades migratorias, el grupo viajaba en condiciones inseguras.</p><p>Los migrantes, en su mayoría de Cuba y Haití, recibieron atención médica. Se confirmó que estaban siendo trasladados por una red de tratantes.</p><p>Las autoridades indicaron que se trata de la tercera operación de rescate del mes.</p>',
      resumen: 'Rescatan 15 migrantes en frontera sur. Recibieron atención médica. Tercera operación del mes.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-06',
      slug: 'rescatan-15-migrantes-frontera-sur',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Rescate con autoridades, nacionalidades y contexto',
  },
  {
    nombre: 'sucesos-11-corto-circuito',
    noticia: {
      titulo: 'Cortocircuito provoca pánico en edificio de Managua',
      contenido: '<p>Un cortocircuito provocó pánico en un edificio de apartamentos en el barrio Las Mercedes de Managua. Los residentes fueron evacuados preventivamente.</p><p>Bomberos confirmaron que el incidente fue controlado rápidamente. No se reportaron heridos ni daños mayores.</p><p>Según testigos, el corto se originó en el tablero principal del edificio.</p>',
      resumen: 'Cortocircuito en edificio de Las Mercedes. Evacuación preventiva sin heridos.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-05',
      slug: 'cortocircuito-edificio-las-mercedes',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 45,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Cortocircuito con testigos y Bomberos',
  },
  {
    nombre: 'sucesos-12-perdida-ganado',
    noticia: {
      titulo: 'Ganadero pierde 30 cabezas de ganado por robo en Chontales',
      contenido: '<p>Un ganadero de Chontales reportó la pérdida de 30 cabezas de ganado tras un robo en su finca. Según el afectado, el robo ocurrió en horas de la madrugada.</p><p>El ganadero indicó que las autoridades fueron notificadas y se inició la búsqueda. El valor estimado de las pérdidas supera los C$200,000.</p><p>Vecinos del sector indicaron que los robos de ganado han aumentado en los últimos meses.</p>',
      resumen: 'Ganadero pierde 30 cabezas por robo en Chontales. Pérdidas superan C$200,000.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-04',
      slug: 'robo-ganado-chontales-30-cabezas',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Robo de ganado con afectado, cantidad y contexto',
  },
  {
    nombre: 'sucesos-13-colision-motocicletas',
    noticia: {
      titulo: 'Dos motociclistas heridos en colisión en Tipitapa',
      contenido: '<p>Dos motociclistas resultaron heridos tras una colisión en la entrada de Tipitapa. Según testigos, una de las motocicletas invadió el carril contrario.</p><p>Los heridos fueron trasladados al centro de salud local. Ambos presentan lesiones pero están fuera de peligro.</p><p>El tránsito en la zona fue afectado por 30 minutos mientras se retiraban los vehículos.</p>',
      resumen: 'Dos motociclistas heridos en colisión en Tipitapa. Trasladados a centro de salud.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-03',
      slug: 'colision-motocicletas-tipitapa',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Colisión con testigos, heridos y ubicación',
  },
  {
    nombre: 'sucesos-14-hallazgo-cuerpo',
    noticia: {
      titulo: 'Cuerpo de persona es hallado en zona rural de Matagalpa',
      contenido: '<p>El cuerpo de una persona fue hallado en una zona rural de Matagalpa. Según familiares, la persona había sido reportada como desaparecida dos días antes.</p><p>Las autoridades iniciaron las investigaciones correspondientes. Medicina Legal realizó el levantamiento del cuerpo.</p><p>Se espera los resultados de la autopsia para determinar las causas del deceso.</p>',
      resumen: 'Cuerpo hallado en zona rural de Matagalpa. Persona reportada desaparecida dos días antes.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-02',
      slug: 'cuerpo-hallado-matagalpa',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Hallazgo con familiares, Medicina Legal y autoridades',
  },
  {
    nombre: 'sucesos-15-pelea-heridos',
    noticia: {
      titulo: 'Pelea deja un herido de gravedad en Jinotega',
      contenido: '<p>Una pelea dejó un herido de gravedad en el barrio San Luis de Jinotega. Según testigos, la pelea inició por una disputa entre vecinos.</p><p>El herido fue trasladado al hospital y recibe atención médica. Las autoridades detuvieron a una persona relacionada con los hechos.</p><p>Vecinos indicaron que es la segunda pelea grave en el sector esta semana.</p>',
      resumen: 'Pelea deja herido grave en barrio San Luis de Jinotega. Una persona detenida.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-07-01',
      slug: 'pelea-herido-jinotega',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Pelea con testigos, herido y detención',
  },
  {
    nombre: 'sucesos-16-explosion-cilindro',
    noticia: {
      titulo: 'Explosión de cilindro de gas daña vivienda en Masaya',
      contenido: '<p>Una explosión de un cilindro de gas causó daños en una vivienda del barrio Monimbó de Masaya. Según vecinos, la explosión se escuchó a varias cuadras de distancia.</p><p>Bomberos acudieron al lugar y confirmaron que no hubo heridos. Los daños se limitaron a la cocina de la vivienda.</p><p>El dueño de la vivienda indicó que el cilindro tenía más de 10 años de uso.</p>',
      resumen: 'Explosión de cilindro daña vivienda en Monimbó, Masaya. Sin heridos.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-06-30',
      slug: 'explosion-cilindro-masaya',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Explosión con vecinos, Bomberos y ubicación',
  },
  {
    nombre: 'sucesos-17-atropello',
    noticia: {
      titulo: 'Peatón es atropellado en carretera a El Crucero',
      contenido: '<p>Un peatón fue atropellado en la carretera a El Crucero. Según testigos, el vehículo huyó del lugar.</p><p>El herido fue trasladado por familiares al hospital más cercano. Su estado es estable.</p><p>Las autoridades buscan al conductor responsable del atropello.</p>',
      resumen: 'Peatón atropellado en carretera a El Crucero. Vehículo huyó del lugar.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-06-29',
      slug: 'atropello-crucero',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 45,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Atropello con testigos y familiares',
  },
  {
    nombre: 'sucesos-18-estafa-comercio',
    noticia: {
      titulo: 'Estafador es captado por cámaras en centro comercial de Managua',
      contenido: '<p>Un estafador fue captado por cámaras de seguridad en un centro comercial de Managua. Según el comercio afectado, el individuo pagó con documentos falsos.</p><p>El comercio indicó que las cámaras registraron al sujeto en el momento de la transacción. Las imágenes fueron entregadas a las autoridades.</p><p>Se estima que el monto de la estafa supera los C$30,000.</p>',
      resumen: 'Estafador captado por cámaras en centro comercial de Managua. Pagó con documentos falsos.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-06-28',
      slug: 'estafador-camaras-centro-comercial',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 45,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Estafa con comercio, cámaras y monto',
  },
  {
    nombre: 'sucesos-19-detenidos-tenencia-armas',
    noticia: {
      titulo: 'Detienen a dos sujetos con armas ilegales en Bluefields',
      contenido: '<p>Dos sujetos fueron detenidos con armas ilegales en Bluefields. Según la Policía, los individuos fueron interceptados en un operativo de rutina.</p><p>Se les decomisaron dos armas de fuego y municiones. Los detenidos serán presentados ante las autoridades.</p><p>Las autoridades indicaron que los sujetos tienen antecedentes por delitos comunes.</p>',
      resumen: 'Dos detenidos con armas ilegales en Bluefields. Decomisan armas y municiones.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-06-27',
      slug: 'detenidos-armas-bluefields',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Detención con Policía, armas y antecedentes',
  },
  {
    nombre: 'sucesos-20-caida-andamio',
    noticia: {
      titulo: 'Obrero resulta herido tras caída de andamio en construcción',
      contenido: '<p>Un obrero resultó herido tras caer de un andamio en una construcción en el barrio Villa Libertad de Managua. Según testigos, el andamio cedió mientras el trabajador realizaba labores en el segundo nivel.</p><p>El herido fue trasladado al hospital y presenta fracturas. Su estado es estable.</p><p>Las autoridades iniciaron una inspección del lugar para verificar las medidas de seguridad.</p>',
      resumen: 'Obrero herido por caída de andamio en Villa Libertad. Trasladado al hospital con fracturas.',
      categoria: 'Sucesos',
      autor: 'Redacción NI',
      fecha: '2025-06-26',
      slug: 'obrero-herido-andamio-villa-libertad',
    },
    categoriaEsperada: 'Sucesos',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Accidente laboral con testigos, ubicación y autoridades',
  },
];

// ───────────────────────────────────────────────
// NACIONALES — 20 casos
// ───────────────────────────────────────────────

export const nacionalesFixtures: TestFixture[] = [
  {
    nombre: 'nacionales-01-programa-vivienda',
    noticia: {
      titulo: 'Gobierno anuncia programa de viviendas para familias de bajos recursos',
      contenido: '<p>El gobierno anunció un nuevo programa de viviendas para familias de bajos recursos en Managua. Según el comunicado, se construirán 500 viviendas en el sector este de la capital.</p><p>Las familias beneficiadas serán seleccionadas mediante un censo socioeconómico. La entrega de las viviendas está prevista para diciembre.</p><p>Según fuentes oficiales, la inversión supera los C$150 millones.</p>',
      resumen: 'Gobierno anuncia construcción de 500 viviendas para familias de bajos recursos en Managua.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-15',
      slug: 'programa-viviendas-gobierno-managua',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Anuncio gubernamental con comunicado, cifras y cronograma',
  },
  {
    nombre: 'nacionales-02-inauguracion-carretera',
    noticia: {
      titulo: 'Inauguran tramo de carretera entre Matagalpa y Jinotega',
      contenido: '<p>Fue inaugurado un nuevo tramo de carretera entre Matagalpa y Jinotega. La obra tiene una extensión de 45 kilómetros y beneficiará a más de 200,000 habitantes.</p><p>Según el Ministerio de Transporte, la inversión fue de C$300 millones. La carretera reduce el tiempo de viaje en 40 minutos.</p><p>Los habitantes de la zona indicaron que la vía era una demanda histórica de la región.</p>',
      resumen: 'Inauguran tramo de 45 km entre Matagalpa y Jinotega. Inversión de C$300 millones.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-14',
      slug: 'inauguran-carretera-matagalpa-jinotega',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Inauguración con Ministerio, cifras y beneficiarios',
  },
  {
    nombre: 'nacionales-03-censo-poblacion',
    noticia: {
      titulo: 'INEC presentará resultados del censo nacional en agosto',
      contenido: '<p>El Instituto Nacional de Información de Desarrollo (INEC) presentará los resultados del censo nacional en agosto. Según el director, los datos incluirán información demográfica de los 15 departamentos y 2 regiones.</p><p>El censo fue realizado en el primer trimestre del año. Se censaron más de 6 millones de habitantes.</p><p>Los resultados permitirán actualizar las políticas públicas del país.</p>',
      resumen: 'INEC presentará resultados del censo en agosto. Más de 6 millones de habitantes censados.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-13',
      slug: 'inec-resultados-censo-agosto',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Censo con INEC, director, cifras y cronograma',
  },
  {
    nombre: 'nacionales-04-plan-educacion',
    noticia: {
      titulo: 'Ministerio de Educación anuncia plan de mejoras escolares',
      contenido: '<p>El Ministerio de Educación anunció un plan de mejoras para 200 escuelas públicas del país. El plan incluye reparación de aulas, dotación de mobiliario y capacitación docente.</p><p>Según el ministro, la inversión será de C$80 millones. Las obras iniciarán en septiembre.</p><p>Los directores de centros educativos indicaron que las mejoras son necesarias tras años de postergación.</p>',
      resumen: 'Educación anuncia mejoras para 200 escuelas. Inversión de C$80 millones desde septiembre.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-12',
      slug: 'plan-mejoras-escuelas-educacion',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Plan con ministro, cifras y cronograma',
  },
  {
    nombre: 'nacionales-05-informe-economia',
    noticia: {
      titulo: 'Banco Central reporta crecimiento del 4.5% en primer semestre',
      contenido: '<p>El Banco Central de Nicaragua reportó un crecimiento económico del 4.5% en el primer semestre del año. Según el informe, los sectores que más aportaron fueron agricultura, manufactura y comercio.</p><p>El presidente del Banco Central indicó que las proyecciones para fin de año se mantienen en 5%. El informe completo será publicado la próxima semana.</p><p>Analistas económicos señalaron que el crecimiento es positivo pero requiere sostenibilidad.</p>',
      resumen: 'Banco Central reporta crecimiento del 4.5% en primer semestre. Proyección anual del 5%.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-11',
      slug: 'crecimiento-45-banco-central',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 60,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Informe con BCN, presidente, cifras y analistas',
  },
  {
    nombre: 'nacionales-06-programa-salud',
    noticia: {
      titulo: 'MINSa amplía cobertura de vacunación en zonas rurales',
      contenido: '<p>El Ministerio de Salud amplió la cobertura de vacunación en zonas rurales del país. Según el comunicado, se vacunarán 50,000 niños en 15 municipios.</p><p>El director del programa indicó que las brigadas médicas llegarán a comunidades remotas. La campaña iniciará en agosto.</p><p>Los líderes comunales indicaron que la medida es importante para la salud infantil.</p>',
      resumen: 'MINSa amplía vacunación: 50,000 niños en 15 municipios rurales desde agosto.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-10',
      slug: 'minsa-vacunacion-zonas-rurales',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Salud con MINSa, director, cifras y cronograma',
  },
  {
    nombre: 'nacionales-07-agua-potable',
    noticia: {
      titulo: 'Enagua inaugura sistema de agua potable en Rivas',
      contenido: '<p>Enagua inauguró un nuevo sistema de agua potable en el municipio de Rivas. El sistema beneficiará a 3,000 familias de la zona urbana.</p><p>Según el director de Enagua, la inversión fue de C$45 millones. El sistema incluye un pozo nuevo y 15 kilómetros de red.</p><p>Los habitantes indicaron que tenían problemas de abastecimiento desde hace años.</p>',
      resumen: 'Enagua inaugura sistema de agua para 3,000 familias en Rivas. Inversión de C$45 millones.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-09',
      slug: 'enagua-agua-potable-rivas',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Inauguración con Enagua, director, cifras y beneficiarios',
  },
  {
    nombre: 'nacionales-08-cooperacion-internacional',
    noticia: {
      titulo: 'Nicaragua firma acuerdo de cooperación con Unión Europea',
      contenido: '<p>Nicaragua firmó un acuerdo de cooperación con la Unión Europea por €50 millones. Los fondos serán destinados a proyectos de desarrollo rural y medio ambiente.</p><p>Según el canciller, el acuerdo fortalece las relaciones bilaterales. Los proyectos iniciarán en 2026.</p><p>El embajador de la UE indicó que el acuerdo es parte de una estrategia regional.</p>',
      resumen: 'Nicaragua firma acuerdo de cooperación con UE por €50 millones para desarrollo rural.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-08',
      slug: 'nicaragua-acuerdo-cooperacion-ue',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 60,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Acuerdo con canciller, embajador, monto y cronograma',
  },
  {
    nombre: 'nacionales-09-elecciones-regionales',
    noticia: {
      titulo: 'Consejo Supremo Electoral convoca a elecciones regionales en Caribe',
      contenido: '<p>El Consejo Supremo Electoral (CSE) convocó a elecciones regionales en la Costa Caribe. Los comicios se realizarán en marzo del próximo año.</p><p>Según el magistrado presidente, se elegirán los consejos regionales autónomos. El calendario electoral será publicado en agosto.</p><p>Los partidos políticos indicaron que iniciarán sus campañas en septiembre.</p>',
      resumen: 'CSE convoca a elecciones regionales en Caribe para marzo del próximo año.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-07',
      slug: 'cse-elecciones-regionales-caribe',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Convocatoria con CSE, magistrado y cronograma',
  },
  {
    nombre: 'nacionales-10-produccion-arroz',
    noticia: {
      titulo: 'Producción de arroz crece 12% en la temporada 2024-2025',
      contenido: '<p>La producción de arroz creció 12% en la temporada 2024-2025 según el Ministerio Agropecuario. Se produjeron 400,000 quintales más que el ciclo anterior.</p><p>Según el ministro, el crecimiento se debe a mejores técnicas de riego y semillas mejoradas. Los principales productores son León y Chinandega.</p><p>Los productores indicaron que los precios se mantienen estables para el consumidor.</p>',
      resumen: 'Producción de arroz crece 12%: 400,000 quintales más en temporada 2024-2025.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-06',
      slug: 'produccion-arroz-crece-12-porcentaje',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Producción con ministro, cifras y productores',
  },
  {
    nombre: 'nacionales-11-turismo-cifras',
    noticia: {
      titulo: 'Turismo reporta llegada de 800,000 visitantes en primer semestre',
      contenido: '<p>El Instituto Nicaragüense de Turismo (INTUR) reportó la llegada de 800,000 visitantes en el primer semestre del año. Esto representa un crecimiento del 15% respecto al año anterior.</p><p>Según la directora de INTUR, los principales mercados son Estados Unidos, Centroamérica y Europa. El turismo generó C$200 millones en divisas.</p><p>Los hoteleros indicaron que la ocupación promedio subió al 70%.</p>',
      resumen: 'INTUR reporta 800,000 visitantes en primer semestre. Crecimiento del 15%.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-05',
      slug: 'turismo-800000-visitantes-primer-semestre',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 60,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Turismo con INTUR, directora, cifras y hoteleros',
  },
  {
    nombre: 'nacionales-12-energia-renovable',
    noticia: {
      titulo: 'Nicaragua alcanza 60% de energía renovable en matriz eléctrica',
      contenido: '<p>Nicaragua alcanzó el 60% de energía renovable en su matriz eléctrica según el Ministerio de Energía y Minas. Las principales fuentes son geotermia, eólica y solar.</p><p>Según el ministro, la meta es llegar al 70% en 2027. Se invertirán C$500 millones en nuevos proyectos.</p><p>Expertos del sector indicaron que Nicaragua es líder regional en energía limpia.</p>',
      resumen: 'Nicaragua alcanza 60% de energía renovable. Meta: 70% en 2027 con C$500 millones.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-04',
      slug: 'energia-renovable-60-porcentaje-nicaragua',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 60,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Energía con ministro, cifras y expertos',
  },
  {
    nombre: 'nacionales-13-exportacion-cafe',
    noticia: {
      titulo: 'Exportaciones de café generan C$300 millones en cosecha 2024-2025',
      contenido: '<p>Las exportaciones de café generaron C$300 millones en la cosecha 2024-2025. Según el Centro de Tramites de Exportaciones, se exportaron 2 millones de quintales.</p><p>Los principales destinos fueron Estados Unidos, Europa y Japón. El precio internacional del café se mantuvo favorable.</p><p>Los productores indicaron que la próxima cosecha podría ser aún mejor.</p>',
      resumen: 'Exportaciones de café: C$300 millones, 2 millones de quintales en cosecha 2024-2025.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-03',
      slug: 'exportacion-cafe-300-millones',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Exportación con cifras, destinos y productores',
  },
  {
    nombre: 'nacionales-14-programa-beca',
    noticia: {
      titulo: 'Gobierno otorga 1,000 becas a estudiantes de zonas rurales',
      contenido: '<p>El gobierno otorgó 1,000 becas a estudiantes de zonas rurales para continuar estudios universitarios. Según el Ministerio de Educación, las becas cubren matrícula y materiales.</p><p>El ministro indicó que el programa busca reducir la desigualdad educativa. Las becas son para 15 universidades del país.</p><p>Los estudiantes beneficiados indicaron que sin la beca no podrían continuar sus estudios.</p>',
      resumen: 'Gobierno otorga 1,000 becas a estudiantes rurales para 15 universidades del país.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-02',
      slug: 'becas-estudiantes-zonas-rurales',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Becas con ministro, cifras y estudiantes',
  },
  {
    nombre: 'nacionales-15-reforestacion',
    noticia: {
      titulo: 'Reforestan 500 hectáreas en reserva natural Tisey-Estanzuela',
      contenido: '<p>Fueron reforestadas 500 hectáreas en la reserva natural Tisey-Estanzuela entre Estelí y Jinotega. Según MARENA, se plantaron 250,000 árboles de especies nativas.</p><p>El director de MARENA indicó que la reforestación cuenta con apoyo de comunidades locales. El proyecto se extenderá por tres años.</p><p>Los habitantes indicaron que la zona había sufrido deforestación en los últimos años.</p>',
      resumen: 'Reforestan 500 hectáreas en Tisey-Estanzuela con 250,000 árboles nativos.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-07-01',
      slug: 'reforestacion-tisey-estanzuela',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Reforestación con MARENA, director, cifras y comunidades',
  },
  {
    nombre: 'nacionales-16-atencion-medica',
    noticia: {
      titulo: 'Hospital inauguró nueva ala de emergencias en León',
      contenido: '<p>El hospital San Juan de Dios de León inauguró una nueva ala de emergencias. La obra tiene 20 camas y equipos modernos de diagnóstico.</p><p>Según el director del hospital, la inversión fue de C$60 millones. La nueva ala atenderá a 200 pacientes diarios.</p><p>Los médicos indicaron que la ampliación reducirá los tiempos de espera.</p>',
      resumen: 'Hospital San Juan de Dios de León inaugura ala de emergencias con 20 camas.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-06-30',
      slug: 'hospital-leon-ala-emergencias',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Inauguración con director, cifras y médicos',
  },
  {
    nombre: 'nacionales-17-mercado-centroamerica',
    noticia: {
      titulo: 'Nicaragua exporta productos lácteos a Centroamérica por C$120 millones',
      contenido: '<p>Nicaragua exportó productos lácteos a Centroamérica por C$120 millones en el primer semestre. Según el Ministerio Agropecuario, los principales destinos fueron El Salvador y Honduras.</p><p>El ministro indicó que el sector lácteo ha crecido 20% en los últimos tres años. Se exportaron 15 millones de litros.</p><p>Los productores indicaron que buscan expandirse al mercado mexicano.</p>',
      resumen: 'Nicaragua exporta lácteos a Centroamérica por C$120 millones. Crecimiento del 20%.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-06-29',
      slug: 'exportacion-lacteos-centroamerica',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Exportación con ministro, cifras y productores',
  },
  {
    nombre: 'nacionales-18-telecomunicaciones',
    noticia: {
      titulo: 'Telecom amplía cobertura de internet a 50 comunidades rurales',
      contenido: '<p>Telecom Nicaragua amplió la cobertura de internet a 50 comunidades rurales del país. Según la empresa, se instalaron 30 antenas en zonas de difícil acceso.</p><p>El director de Telecom indicó que la inversión fue de C$25 millones. Las comunidades están en Jinotega, Matagalpa y la Costa Caribe.</p><p>Los habitantes indicaron que ahora pueden acceder a servicios educativos en línea.</p>',
      resumen: 'Telecom lleva internet a 50 comunidades rurales con 30 antenas. C$25 millones.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-06-28',
      slug: 'telecom-internet-comunidades-rurales',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 50,
    veredictoEsperado: 'publicar_breve',
    descripcion: 'Telecom con director, cifras y beneficiarios',
  },
  {
    nombre: 'nacionales-19-cultura-patrimonio',
    noticia: {
      titulo: 'UNESCO evalúa declarar patrimonio a ciudad colonial de León',
      contenido: '<p>La UNESCO evalúa declarar patrimonio de la humanidad a la ciudad colonial de León. Según el Ministerio de Cultura, la evaluación iniciará en septiembre.</p><p>El ministro indicó que León cuenta con 12 iglesias coloniales y patrimonio arquitectónico único. La declaratoria impulsaría el turismo.</p><p>Los historiadores indicaron que la ciudad tiene más de 400 años de historia.</p>',
      resumen: 'UNESCO evalúa declarar patrimonio a León colonial. Evaluación inicia en septiembre.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-06-27',
      slug: 'unesco-patrimonio-leon',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 55,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Cultura con UNESCO, ministro, cifras e historiadores',
  },
  {
    nombre: 'nacionales-20-seguridad-ciudadana',
    noticia: {
      titulo: 'Policía reporta disminución del 18% en delitos durante primer semestre',
      contenido: '<p>La Policía Nacional reportó una disminución del 18% en delitos durante el primer semestre del año. Según el informe, los delitos comunes pasaron de 3,200 a 2,624 casos.</p><p>El jefe policial indicó que la reducción se debe a operativos en zonas de mayor incidencia. Se reforzaron 25 barrios a nivel nacional.</p><p>Los líderes comunales indicaron que perciben mayor seguridad en sus barrios.</p>',
      resumen: 'Policía reporta 18% menos delitos en primer semestre. 25 barrios reforzados.',
      categoria: 'Nacionales',
      autor: 'Redacción NI',
      fecha: '2025-06-26',
      slug: 'policia-delitos-18-porcentaje-menos',
    },
    categoriaEsperada: 'Nacionales',
    scoreMinimo: 60,
    veredictoEsperado: 'publicar_estandar',
    descripcion: 'Seguridad con Policía, jefe, cifras y líderes comunales',
  },
];
