// Artículos evergreen adicionales de alto volumen de búsqueda
export const EVERGREEN_ARTICLES_ADDITIONAL = [
  {
    slug: 'salario-minimo-nicaragua-2026-tabla-completa',
    title: 'Salario mínimo Nicaragua 2026: tabla completa por sector y categoría',
    description: 'Cuánto es el salario mínimo en Nicaragua en 2026. Tabla actualizada por sector: agropecuario, servicios, industria, comercio, construcción y hogar.',
    category: 'Economía',
    author: 'Keyling Elieth Rivera Muñoz',
    authorSlug: 'keyling-rivera',
    publishedDate: '2026-01-05',
    updatedDate: '2026-06-17',
    content: `<h2>Salario mínimo en Nicaragua 2026</h2><p>El salario mínimo en Nicaragua para 2026 fue ajustado por el Ministerio del Trabajo (MITRAB) en enero. Los valores varían según el sector económico y la categoría del trabajador.</p><h2>Tabla de salarios mínimos 2026</h2><table style="width:100%;border-collapse:collapse;margin:16px 0;"><thead><tr style="background:var(--primary);color:#fff;"><th style="padding:10px;text-align:left;">Sector</th><th style="padding:10px;text-align:right;">Mensual (C$)</th><th style="padding:10px;text-align:right;">Diario (C$)</th></tr></thead><tbody><tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:10px;">Agropecuario y ganadero</td><td style="padding:10px;text-align:right;">7,185.71</td><td style="padding:10px;text-align:right;">287.43</td></tr><tr style="border-bottom:1px solid #e5e7eb;background:#f9fafb;"><td style="padding:10px;">Servicios, industria y comercio</td><td style="padding:10px;text-align:right;">8,179.43</td><td style="padding:10px;text-align:right;">327.18</td></tr><tr style="border-bottom:1px solid #e5e7eb;"><td style="padding:10px;">Construcción, minas y canteras</td><td style="padding:10px;text-align:right;">9,173.15</td><td style="padding:10px;text-align:right;">366.93</td></tr><tr style="border-bottom:1px solid #e5e7eb;background:#f9fafb;"><td style="padding:10px;">Trabajadores del hogar (jornada completa)</td><td style="padding:10px;text-align:right;">5,500.00</td><td style="padding:10px;text-align:right;">220.00</td></tr><tr><td style="padding:10px;">Centrales azucareras (zafra)</td><td style="padding:10px;text-align:right;">9,500.00</td><td style="padding:10px;text-align:right;">380.00</td></tr></tbody></table><p style="font-size:0.9rem;color:var(--gray-500);"><em>Nota: valores oficiales MITRAB enero 2026. El tipo de cambio referencia: C$ 36.65 = USD 1.00</em></p><h2>¿Quién define el salario mínimo?</h2><p>El Consejo Nacional del Salario Mínimo, conformado por representantes del gobierno, empresarios y sindicatos, negocia y fija los ajustes anuales. El Ministerio del Trabajo (MITRAB) publica los valores oficiales en el <em>La Gaceta</em>.</p><h2>¿Qué pasa si un empleador paga menos?</h2><p>Pagar por debajo del salario mínimo es una infracción laboral sancionable. Los trabajadores pueden denunciar en:</p><ul><li>Delegaciones regionales del MITRAB en cada departamento</li><li>Línea telefónica del MITRAB: 1800-1000-800 (llamada gratuita)</li><li>Oficina de atención al ciudadano en Managua</li></ul><h2>Diferencia entre salario mínimo y salario promedio</h2><p>El salario mínimo es el piso legal. El salario promedio en Nicaragua ronda los C$ 12,000-15,000 mensuales en sectores formales, aunque la informalidad laboral representa más del 60% de la población económicamente activa.</p>`,
    faqs: [
      { question: '¿Cuál es el salario mínimo mensual en Nicaragua 2026?', answer: 'Para servicios, industria y comercio es de C$ 8,179.43 mensuales (C$ 327.18 diarios). El sector agropecuario tiene el mínimo más bajo: C$ 7,185.71 mensuales.' },
      { question: '¿Se aplica el salario mínimo a trabajadores informales?', answer: 'El salario mínimo solo aplica a relaciones laborales formales. Sin embargo, el MITRAB ha intensificado inspecciones en sectores informales como comercio y construcción.' },
      { question: '¿Cuándo se actualiza el salario mínimo?', answer: 'El Consejo Nacional del Salario Mínimo se reúne anualmente, generalmente en diciembre-enero, para fijar los valores del año siguiente.' },
    ],
  },
];
